#!/usr/bin/env python3
"""Emit a self-contained shell script for running Path 2 in sandbox mode.

When the skill runs in Cowork's sandbox, Path 2 (WhisperX local) cannot
execute inside the sandbox — it needs the user's real machine. This module
generates a shell script that the user runs from their local terminal.
"""

import sys
import json
from pathlib import Path
from datetime import datetime

# Add parent directories to path for lib imports
current_file = Path(__file__).resolve()
plugin_root = current_file.parent.parent.parent.parent
sys.path.insert(0, str(plugin_root / "lib"))

try:
    from host_mode import get_mdpowers_data_dir
except ImportError:
    print("ERROR: Could not import lib.host_mode. Ensure the mdpowers plugin structure is correct.")
    sys.exit(1)


def emit_run_script(
    pathway: str,
    source: str,
    out_path: str,
    host_plugin_dir: str,
    host_out_dir: str,
    vocab_overlay: str | None = None,
    num_speakers: int | None = None,
    speakers_override: str | None = None,
    cookies_file: str | None = None,
    workspace_root: Path | None = None,
) -> Path:
    """Generate a shell script for running Path 2 (WhisperX) locally.

    Args:
        pathway: runner name (e.g., 'run_path2_whisperx')
        source: source audio file path (sandbox-side)
        out_path: output directory (sandbox-side)
        host_plugin_dir: full path to plugin on host machine
        host_out_dir: full path to output dir on host machine
        vocab_overlay: optional path to vocab overlay (host-side)
        num_speakers: optional speaker count
        speakers_override: optional comma-separated speaker names
        cookies_file: optional cookies file path (host-side)
        workspace_root: where to write the script (defaults to current dir)

    Returns:
        Path to the generated script file in workspace_root
    """
    if workspace_root is None:
        workspace_root = Path.cwd()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    script_name = f"run_transcribe_{timestamp}.sh"
    script_path = workspace_root / script_name

    # Build the command
    cmd_parts = [
        f'cd "{host_plugin_dir}"',
        f'python3 scripts/{pathway}.py "{source}" \\',
        f'    --out "{host_out_dir}" \\',
    ]

    if vocab_overlay:
        cmd_parts.append(f'    --vocab-overlay "{vocab_overlay}" \\')
    if num_speakers is not None:
        cmd_parts.append(f'    --num-speakers {num_speakers} \\')
    if speakers_override:
        cmd_parts.append(f'    --speakers "{speakers_override}" \\')
    if cookies_file:
        cmd_parts.append(f'    --cookies-file "{cookies_file}" \\')

    cmd_parts.append('    --auto')

    command = "\n".join(cmd_parts)

    # Build script content
    script_content = f"""#!/bin/bash
# Generated by mdpowers transcribe skill on {datetime.now().isoformat()}
#
# This script runs Path 2 (WhisperX local transcription) on your machine.
# The Cowork sandbox cannot execute heavy ML workloads directly.
#
# To run: bash {script_name}

set -e

echo "Starting WhisperX transcription..."
echo ""

{command}

echo ""
echo "Done! Transcript saved to:"
echo "  {host_out_dir}"
echo ""
echo "Return to your Cowork session to review the output."
"""

    # Write the script
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return script_path


def build_chat_message(
    script_path_sandbox: str,
    script_path_host: str,
    source_title: str,
    expected_runtime: str,
) -> str:
    """Build a formatted message for the user to run the script locally.

    Args:
        script_path_sandbox: relative path in sandbox (for computer: link)
        script_path_host: absolute path on host (for copy-paste)
        source_title: audio file name or title
        expected_runtime: estimated duration (e.g., "5-10 minutes")

    Returns:
        Formatted markdown message for the skill to surface to the user
    """
    message = f"""Path 2 (WhisperX local) needs to run on your real machine, not in the sandbox.

I've prepared a script to transcribe "{source_title}".

**Option 1: Click to run** (opens terminal)
[Run transcription](computer://{script_path_sandbox})

**Option 2: Copy-paste to your terminal**
```bash
bash {script_path_host}
```

Expected runtime: **{expected_runtime}**

When it's done, come back to this Cowork session and I'll review the output for you.
"""
    return message


def main():
    """Test/demo function."""
    import tempfile

    # Example parameters
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)

        script_path = emit_run_script(
            pathway="run_path2_whisperx",
            source="/tmp/audio.wav",
            out_path="/tmp/output",
            host_plugin_dir="/Users/monty/plugins/mdpowers-plugin",
            host_out_dir="/Users/monty/transcripts",
            vocab_overlay="/Users/monty/.config/mdpowers/vocabulary.custom.json",
            num_speakers=2,
            speakers_override="Alice, Bob",
            workspace_root=tmpdir_path,
        )

        print(f"Generated script: {script_path}")
        print(f"\nScript contents:\n")
        print(script_path.read_text())

        message = build_chat_message(
            script_path_sandbox=str(script_path.relative_to(tmpdir_path)),
            script_path_host=str(script_path),
            source_title="meeting-2026-04-10.m4a",
            expected_runtime="5-10 minutes",
        )

        print(f"\nChat message:\n")
        print(message)


if __name__ == "__main__":
    main()
